### ISSUE TITLE
Accessing MMC4-core

### ISSUE THREAD

**Issue by wusize** [allenai/mmc4#22]
Hi! Thanks so much for your dataset! I want to get access to the MMC4-core (without the fewer-face restriction). However, the [form ](https://forms.gle/VYtcNY8aYaUANK9f8)you previously provided is invalid now. Is there any other means to get the access?

**Comment by jmhessel** [comment]
Hi!

Thanks for flagging this. I made a new form --- here's the link. I will update the readme ASAP.

https://forms.gle/CUesSpXu7xeXZYKp8

Jack

**Comment by jmhessel** [comment]
(the readme has been updated, but I can't close this issue because I do not have the permissions in the AI2 org anymore :( )
