### ISSUE TITLE
add download script for fewer_facev2 and fewer_face_corev3

### ISSUE THREAD

**Issue by Luodian** [allenai/mmc4#3]
Hi Jack and Wanrong, thank you for providing this valuable dataset!

I'm currently utilizing the data to experiment with the openflamingo model and have written a download script for the currently released splits (fewer_faces_v2 and fewer_faces_core_v3). This should help other users quickly prepare and access this dataset.

I've created PR #2, and I hope it contributes positively to the project.

**Comment by HenryHZY** [comment]
That's great:)

**Comment by Luodian** [comment]
I made a change to the download script, because I saw flamingo's data preprocessing script use *.zip file. 

To make it more compatible, I comment out the unzip process.

**Comment by jmhessel** [comment]
(merged!, thanks @Luodian )
