### ISSUE TITLE
Any plan to release the data processing code?

### ISSUE THREAD

**Issue by duzx16** [allenai/mmc4#4]
Thank you for your great work. I am wondering whether you plan to release the data processing code. With the code released, people can process other datasets based on web pages beyond C4.

**Comment by jmhessel** [comment]
Hi @duzx16 ! We are considering releasing more code --- currently, many of the scripts are formatted for running on ai2 clusters, so, may not be useful in raw form for public use. Do you have a sense of which pieces would be most helpful to release (e.g., alignment code, nsfw classifier, low-cost face "this image may contain a face" detector, or ...?)

**Comment by duzx16** [comment]
> Hi @duzx16 ! We are considering releasing more code --- currently, many of the scripts are formatted for running on ai2 clusters, so, may not be useful in raw form for public use. Do you have a sense of which pieces would be most helpful to release (e.g., alignment code, nsfw classifier, low-cost face "this image may contain a face" detector, or ...?)

@jmhessel  I think the deduplication and the nsfw classifier will be most useful since there are many details to reproduce. The nsfw classifier is also helpful in other scenarios. I am not sure  whether it is open-sourced in the laion-5B paper.

**Comment by 152334H** [comment]
+1

**Comment by jmhessel** [comment]
Sorry for the very delayed reply. The NSFW detector is the same as released in this library:
- https://github.com/mlfoundations/dataset2metadata

the deduplication, as mentioned in the writeup, is:
- https://gitlab.com/opennota/findimagedupes

**Comment by miguelusque** [comment]
Hi @jmhessel , I am also interested in the data processing code. I was wondering if you have finally released it. Thanks! (I am also curious about your original C4 data processing code too). Thanks!

**Comment by jmhessel** [comment]
Hi @miguelusque ! Which preprocessing code were you specifically looking for? The NSFW detector and deduplication is linked above. I am planning to release the fast face detection code if you're waiting on that.
