### ISSUE TITLE
Any recommended code for converting mmc4 into WebDataset format instead of jsonl format?

### ISSUE THREAD

**Issue by roboswell** [allenai/mmc4#5]
I noticed that when downloading mmc4-ff, it downloads jsonl files. However, the Open Flamingo model requires dataset shards for training to be in WebDataset format. Could you please recommend code for converting jsonl database files into WebDataset shard format?

**Comment by jmhessel** [comment]
cc @anas-awadalla

**Comment by anas-awadalla** [comment]
Yes will share a [script](https://github.com/mlfoundations/open_flamingo/issues/168) soon :)

**Comment by anas-awadalla** [comment]
The script is [here](https://github.com/mlfoundations/open_flamingo/blob/main/open_flamingo/train/convert_mmc4_to_wds.py) thank you!

**Comment by roboswell** [comment]
@anas-awadalla Presently the script you wrote only allows for 2 inputs as arguments (image_shards and doc_shards). Will you be modifying the script soon to allow for CLIP feature shards rather than image_shards?
Thanks!

**Comment by anas-awadalla** [comment]
The CLIP features are not suitable for training Flamingo models so for now I will be keeping it as is. My suggested workflow be to download raw images using this [script](https://github.com/allenai/mmc4/blob/main/scripts/download_images.py) and then convert those to webdataset shards.

**Comment by roboswell** [comment]
Hi @anas-awadalla, could you help me understand more why the CLIP features for mmc4 are unable to be used for training even though they were (I assume) the same CLIP features you used to train the Open Flamingo 9B vision encoder? I've already downloaded many thousands of the https://storage.googleapis.com/ai2-jackh-mmc4-public/images/clip_vitl14_shard_{$SHARD}_features.pkl files, and would prefer to not let all that time I spent downloading them to have gone to waste.

**Comment by anas-awadalla** [comment]
Yep. First, I apologize for the confusion regarding the CLIP embeddings (I think I mentioned they could be used to train flamingo models in an OpenFlamingo issue). This was a misunderstanding on my end. What you will need to to create the image tokens for Flamingo is the patch embeddings from the vision encoder of CLIP. However, the embeddings in mmc4 are the projection vector of the image to the multimodal space.

One thing I want to point out is that we do not train any vision encoder and instead use this [pre-trained CLIP model](https://huggingface.co/openai/clip-vit-large-patch14).

**Comment by jmhessel** [comment]
closing this as addressed, feel free to re-open if I'm misreading
